import { Context, Session } from 'koishi';
import { Sat } from './types';
export declare class SAT extends Sat {
    config: Sat.Config;
    private apiClient;
    private memoryManager;
    private ChannelParallelCount;
    private onlineUsers;
    constructor(ctx: Context, config: Sat.Config);
    private getAPIConfig;
    private getMemoryConfig;
    private getMiddlewareConfig;
    private getFavorabilityConfig;
    private registerCommands;
    private handleSatCommand;
    private handleAuxiliaryDialogue;
    private checkFavorabilityBlock;
    private performPreChecks;
    private checkDuplicateDialogue;
    private handleFixedDialoguesCheck;
    private checkUserDialogueCount;
    private updateChannelParallelCount;
    private getChannelParallelCount;
    private processInput;
    private generateResponse;
    private buildMessages;
    private buildSystemPrompt;
    private formatResponse;
    private clearSession;
    private addCommonSense;
    private handleUserLevel;
    private handleUserUsage;
    handleMiddleware(session: Session, prompt: string): Promise<string>;
}
export default SAT;
